log:
    pretty: true
    level: debug
grpcmockserver:
    enable: true
    address: 0.0.0.0:30002
    protomanager:
        protoimportpaths: [ ]
        protodir: ./apis
httpmockserver:
    enable: true
    address: 0.0.0.0:30003
apimanager:
    grpcaddress: 0.0.0.0:30000
    httpaddress: 0.0.0.0:30001
pluginregistry: { }
plugin:
    simple: { }
    grpc: { }
    http: { }
    redis:
        enable: false
        addr: 127.0.0.1:6379
        password: ""
        db: 0
        prefix: /powermock/
    rediscluster:
        enable: false
        addresses:
            - xxx.xx.xx.xx:7028
            - xxx.xx.xx.xx:7027
            - xxx.xx.xx.xx:7029
            - xxx.xx.xx.xx:7029
            - xxx.xx.xx.xx:7026
            - xxx.xx.xx.xx:7028
        password: ""
        prefix: /powermock/